[theme]
primaryColor = "#00A844"            # Azul elegante para acentos y botones
backgroundColor = "#F3F1EC"         # Fondo blanco perla
secondaryBackgroundColor = "#FFFFFF" # Cards y contenedores
textColor = "#000000"               # Texto principal oscuro suave
