[theme]
primaryColor = "#00A844"            # Azul elegante para acentos y botones
backgroundColor = "#FFFFFF"         # Fondo blanco perla
secondaryBackgroundColor = "#F3F1EC" # Cards y contenedores
textColor = "#607D8B"               # Texto principal oscuro suave
