[theme]
primaryColor = "#2563eb" # Tu Ónix Acero para resaltar
backgroundColor = "#0B1114" # Tu Ónix base
secondaryBackgroundColor = "#0B1114" # El tono "un poco más claro" para hovers
textColor = "#FFFFFF"
