[theme]
# Azul pizarra de tu botón original para acentos y botones
primaryColor = "#546E7A"           

# Fondo profundo para la aplicación
backgroundColor = "#384A52"        

# Color para las cards y contenedores (Azul grisáceo oscuro)
secondaryBackgroundColor = "#ffffff" 

# Texto principal en Blanco Perla Ultra Chic
textColor = "#F9F6F2"              

# Color de los widgets (se adapta al gris azulado para coherencia)
# font = "sans serif"
