[theme]
primaryColor = "#2563EB"            # Azul elegante para acentos y botones
backgroundColor = "#F3F1EC"         # Fondo blanco perla
secondaryBackgroundColor = "#FFFFFF" # Cards y contenedores
textColor = "#1F1F1F"               # Texto principal oscuro suave
